// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Mproducto application
Backend service


    Schemes:
      http
    Host: localhost:3001
    BasePath: /api
    Version: 0.0.1

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
