swagger: "2.0"
schemes:
    - http
host: localhost:3001
basePath: /api
consumes:
    - application/json
produces:
    - application/json
info:
    description: Backend service
    title: Mproducto application
    version: 0.0.1
securityDefinitions:
    api_key:
        type: apiKey
        in: header
        name: API-Key
security:
    -
        api_key: []
paths:
    /login:
        post:
            security: []   # No security
            summary: Login with user name and password
            parameters:
                -   name:     credentials
                    in:       body
                    required: true
                    schema:
                        type: object
                        required:
                            - name
                            - password
                        properties:
                            name:
                                type: string
                                description: user name
                                minLength: 1
                            password:
                                type: string
                                description: valid password
                                minLength: 1
            responses:
                default: {$ref: '#/responses/Error'}
                '200':
                    description: The api token of the user
                    schema:
                        $ref: '#/definitions/ApiKey'
    /user:
        get:
            summary: Show user profile
            responses:
                default: {$ref: '#/responses/Error'}
                '200':
                    description: User profile
                    schema:
                        $ref: '#/definitions/User'
        put:
            security: []   # No security
            summary: Add new user
            parameters:
                -   name: newUser
                    in: body
                    required: true
                    schema:
                        type: object
                        required:
                            - name
                            - email
                            - password
                        properties:
                            name:
                                type: string
                                description: user name
                                minLength: 1
                            email:
                                type: string
                                description: user email
                                minLength: 1
                            password:
                                type: string
                                description: valid password
                                minLength: 1

            responses:
                default: {$ref: '#/responses/Error'}
                '201':
                    description: The api token of the new user
                    schema:
                        $ref: '#/definitions/ApiKey'
    /catalogue:
        get:
            security: []   # No security
            summary: Show catalogue of products
            responses:
                default: {$ref: '#/responses/Error'}
                '200':
                    description: Catalogue of products
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/CatalogueNode'
    /products:
        get:
            security: []   # No security
            summary: Show products by tags
            parameters:
                -   in:       query
                    name:     tags
                    required: true
                    type: array
                    items:
                        type: string
                        minLength: 1

            responses:
                default: {$ref: '#/responses/Error'}
                '200':
                    description: Catalogue of products
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/Product'
responses:
    # Return general errors using same model as used by go-swagger for validation errors.
    Error:
        description: Error
        schema:
            $ref: '#/definitions/Error'
definitions:
    # This model should match output of api.ServeError handler, to ensure
    # errors returned by go-swagger (like failed validation) use same
    # format as general errors returned by our handlers.
    # By default api.ServeError = github.com/go-openapi/errors.ServeError.
    Error:
        type: object
        required:
            - code
            - message
        properties:
            code:
                description: Either same as HTTP Status Code OR >= 600 with HTTP Status Code 422
                type: integer
                format: int32
            message:
                type: string
    ApiKey:
        description: Valid api key
        type: object
        required:
            - apiKey
        properties:
            apiKey:
                type: string
                description: Valid api key value
                minLength: 1
                x-isnullable: false
    User:
        description: The profile of the user
        type: object
        required:
            - name
            - email
        properties:
            name:
                type: string
                description: user name
                minLength: 1
                x-isnullable: false
            email:
                type: string
                description: user email
                minLength: 1
                x-isnullable: false
    CatalogueNode:
        description: The catalogue of products
        type: object
        required:
            - id
            - name
            - tags
            - nodes
        properties:
            id:
                type: integer
                format: int32
                description: node id
                minimum: 1
                x-isnullable: false
            name:
                type: string
                description: The title of catalogue
                minLength: 1
                x-isnullable: false
            tags:
                description: The tags list of products
                type: array
                items:
                    type: string
                    minLength: 1
            nodes:
                description: Subcatalogues of this catalogue
                type: array
                items:
                    $ref: '#/definitions/CatalogueNode'
    Product:
        type: object
        description: Product
        required:
            - name
            - id
        properties:
            name:
                type: string
                description: product name
                minLength: 1
                x-isnullable: false
            id:
                type: integer
                format: int64
                description: product id
                minimum: 1
                x-isnullable: false