// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	model "github.com/fpawel/mproducto/internal/api/model"
)

// ListProductsByTagsOKCode is the HTTP code returned for type ListProductsByTagsOK
const ListProductsByTagsOKCode int = 200

/*ListProductsByTagsOK Catalogue of products

swagger:response listProductsByTagsOK
*/
type ListProductsByTagsOK struct {

	/*
	  In: Body
	*/
	Payload []*model.Product `json:"body,omitempty"`
}

// NewListProductsByTagsOK creates ListProductsByTagsOK with default headers values
func NewListProductsByTagsOK() *ListProductsByTagsOK {

	return &ListProductsByTagsOK{}
}

// WithPayload adds the payload to the list products by tags o k response
func (o *ListProductsByTagsOK) WithPayload(payload []*model.Product) *ListProductsByTagsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list products by tags o k response
func (o *ListProductsByTagsOK) SetPayload(payload []*model.Product) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListProductsByTagsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*model.Product, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*ListProductsByTagsDefault Error

swagger:response listProductsByTagsDefault
*/
type ListProductsByTagsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *model.Error `json:"body,omitempty"`
}

// NewListProductsByTagsDefault creates ListProductsByTagsDefault with default headers values
func NewListProductsByTagsDefault(code int) *ListProductsByTagsDefault {
	if code <= 0 {
		code = 500
	}

	return &ListProductsByTagsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list products by tags default response
func (o *ListProductsByTagsDefault) WithStatusCode(code int) *ListProductsByTagsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list products by tags default response
func (o *ListProductsByTagsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list products by tags default response
func (o *ListProductsByTagsDefault) WithPayload(payload *model.Error) *ListProductsByTagsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list products by tags default response
func (o *ListProductsByTagsDefault) SetPayload(payload *model.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListProductsByTagsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
