// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ListProductsByTagsHandlerFunc turns a function with the right signature into a list products by tags handler
type ListProductsByTagsHandlerFunc func(ListProductsByTagsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListProductsByTagsHandlerFunc) Handle(params ListProductsByTagsParams) middleware.Responder {
	return fn(params)
}

// ListProductsByTagsHandler interface for that can handle valid list products by tags params
type ListProductsByTagsHandler interface {
	Handle(ListProductsByTagsParams) middleware.Responder
}

// NewListProductsByTags creates a new http.Handler for the list products by tags operation
func NewListProductsByTags(ctx *middleware.Context, handler ListProductsByTagsHandler) *ListProductsByTags {
	return &ListProductsByTags{Context: ctx, Handler: handler}
}

/*ListProductsByTags swagger:route GET /products listProductsByTags

Show products by tags

*/
type ListProductsByTags struct {
	Context *middleware.Context
	Handler ListProductsByTagsHandler
}

func (o *ListProductsByTags) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListProductsByTagsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
