// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	model "github.com/fpawel/mproducto/internal/api/model"
)

// PutUserCreatedCode is the HTTP code returned for type PutUserCreated
const PutUserCreatedCode int = 201

/*PutUserCreated The api token of the new user

swagger:response putUserCreated
*/
type PutUserCreated struct {

	/*
	  In: Body
	*/
	Payload *model.APIKey `json:"body,omitempty"`
}

// NewPutUserCreated creates PutUserCreated with default headers values
func NewPutUserCreated() *PutUserCreated {

	return &PutUserCreated{}
}

// WithPayload adds the payload to the put user created response
func (o *PutUserCreated) WithPayload(payload *model.APIKey) *PutUserCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put user created response
func (o *PutUserCreated) SetPayload(payload *model.APIKey) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutUserCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PutUserDefault Error

swagger:response putUserDefault
*/
type PutUserDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *model.Error `json:"body,omitempty"`
}

// NewPutUserDefault creates PutUserDefault with default headers values
func NewPutUserDefault(code int) *PutUserDefault {
	if code <= 0 {
		code = 500
	}

	return &PutUserDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the put user default response
func (o *PutUserDefault) WithStatusCode(code int) *PutUserDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the put user default response
func (o *PutUserDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the put user default response
func (o *PutUserDefault) WithPayload(payload *model.Error) *PutUserDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put user default response
func (o *PutUserDefault) SetPayload(payload *model.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutUserDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
