// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// APIKey Valid api key
// swagger:model ApiKey
type APIKey struct {

	// Valid api key value
	// Required: true
	// Min Length: 1
	APIKey string `json:"apiKey"`
}

// Validate validates this Api key
func (m *APIKey) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAPIKey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIKey) validateAPIKey(formats strfmt.Registry) error {

	if err := validate.RequiredString("apiKey", "body", string(m.APIKey)); err != nil {
		return err
	}

	if err := validate.MinLength("apiKey", "body", string(m.APIKey), 1); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIKey) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIKey) UnmarshalBinary(b []byte) error {
	var res APIKey
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
